# ---------------------- POSTGRESQL - DEPLOYMENT ------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: 'demo'
            - name: POSTGRES_PASSWORD
              value: 'demo'
            - name: POSTGRES_DB
              value: 'demo'

---
# ---------------------- BIZ - DEPLOYMENT ------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biz
spec:
  replicas: 1
  selector:
    matchLabels:
      name: biz
  template:
    metadata:
      labels:
        name: biz
    spec:
      containers:
        - name: biz
          image: dkabh/biz:run
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          env:
            - name: BIZ_PORT
              value: '9001'
            - name: DB_URL
              value: 'jdbc:postgresql://$(POSTGRES_SERVICE_HOST):5432'
            - name: DB_NAME
              value: 'demo'
            - name: DB_USER
              value: 'demo'
            - name: DB_PASSWORD
              value: 'demo'

# ---------------------- ADMIN - DEPLOYMENT ------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: admin
  template:
    metadata:
      labels:
        name: admin
    spec:
      containers:
        - name: admin
          image: dkabh/admin:run
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9101
          env:
            - name: BIZ_URL
              value: "$(BIZ_SERVICE_HOST)"
            - name: BIZ_PORT
              value: "$(BIZ_SERVICE_PORT)"
            - name: ADMIN_PORT
              value: "9101"

# ---------------------- NEWS - DEPLOYMENT ------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
spec:
  replicas: 1
  selector:
    matchLabels:
      name: news
  template:
    metadata:
      labels:
        name: news
    spec:
      containers:
        - name: news
          image: dkabh/news:run
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9201
          env:
            - name: BIZ_URL
              value: "http://192.168.99.113"
            - name: BIZ_PORT
              value: "30001"
            - name: NEWS_PORT
              value: "9201"

# ---------------------- WEBSITE - DEPLOYMENT ------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      name: website
  template:
    metadata:
      labels:
        name: website
    spec:
      containers:
        - name: website
          image: dkabh/website:run
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9301
          env:
            - name: ADMIN_URL
              value: "http://192.168.99.113"
            - name: ADMIN_PORT
              value: "30101"
            - name: NEWS_URL
              value: "http://192.168.99.113"
            - name: NEWS_PORT
              value: "30201"
            - name: WEBSITE_PORT
              value: "9301"

#---
## ---------------------- MONITOR - DEPLOYMENT ------------------------------
#apiVersion: apps/v1
#kind: Deployment
#metadata:
  #name: monitor
#spec:
  #replicas: 1
  #selector:
    #matchLabels:
      #name: monitor
  #template:
    #metadata:
      #labels:
        #name: monitor
    #spec:
      #containers:
        #- name: monitor
          #image: dkabh/monitor:run
          #imagePullPolicy: IfNotPresent
          #ports:
            #- containerPort: 8201
          #env:
            #- name: MONITOR_PORT
              #value: "8201"
