#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
  #name: demo-ingress
  #annotations:
    #nginx.ingress.kubernetes.io/configuration-snippet: |
      #rewrite / http://demoapp.abh:30301/ui$uri permanent;
#spec:
  #rules:
  #- http:
      #paths:
      #- path: /
        #backend:
          #serviceName: website
          #servicePort: 9301
