{{- if .Values.admin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.svc.name }}
spec:
  selector:
    name: admin
  ports:
    - protocol: TCP
      port: {{ .Values.admin.svc.port }}
      nodePort: {{ .Values.admin.svc.nodePort }}
      name: admin
  type: {{ .Values.admin.svc.type }}
{{- end }}
