{{- if .Values.news.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.news.svc.name }}
spec:
  selector:
    name: news
  ports:
    - protocol: TCP
      port: {{ .Values.news.svc.port }}
      targetPort: {{ .Values.news.svc.port }}
      name: news
  type: {{ .Values.news.svc.type }}
{{- end }}
