apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.svc.name }}
spec:
  selector:
    name: website
  ports:
    - protocol: TCP
      port: {{ .Values.website.svc.port }}
      nodePort: {{ .Values.website.svc.nodePort }}
      name: website
  type: {{ .Values.website.svc.type }}