{{- if .Values.website.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.svc.name }}
spec:
  selector:
    name: website
  ports:
    - protocol: TCP
      port: {{ .Values.website.svc.port }}
      targetPort: {{ .Values.website.svc.port }}
      name: website
  type: {{ .Values.website.svc.type }}
{{- end }}