url: 'http://demoapp.abh'

# ----- Ingress -----

ingress:
  enabled: true
  name: 'website-ingress'
  host: 'demoapp.abh'
  website:
    path: "/ui"
    serviceName: 'website-svc'
    servicePort: '9301'
  news:
    path: "/news"
    serviceName: 'news-svc'
    servicePort: '9201'
  admin:
    path: "/admin"
    serviceName: 'admin-svc'
    servicePort: '9101'

# ----- Secrets -----

secrets:
  username:
  password:
  db:

# ----- PostgreSQL -----

postgres:
  enabled: true
  dep:
    name: 'postgres'
    labelName: 'postgres'
    replicaCount: 1
    image: 'postgres:10'
    imagePullPolicy: 'IfNotPresent'
    containerPort: '5432'
  svc:
    name: 'postgres-svc'
    port: '5432'
    type: 'ClusterIP'

# ----- Biz -----

biz:
  enabled: true
  dep:
    name: 'biz'
    labelName: 'biz'
    replicaCount: 1
    image: 'dkabh/biz:run'
    imagePullPolicy: 'IfNotPresent'
    containerPort: '9001'
    dbURL: 'jdbc:postgresql://postgres-svc:5432'
  svc:
    name: 'biz-svc'
    port: '9001'
    type: 'ClusterIP'

# ----- Website -----

website:
  websiteUrl: 'http://demoapp.abh/ui'
  enabled: false
  dep:
    name: 'website'
    labelName: 'website'
    replicaCount: 1
    image: 'dkabh/website:run'
    imagePullPolicy: 'IfNotPresent'
    containerPort: '9301'
  svc:
    name: 'website-svc'
    port: '9301'
    type: 'ClusterIP'

# ----- Admin -----

admin:
  enabled: false
  adminUrl: 'http://demoapp.abh/admin'
  dep:
    name: 'admin'
    labelName: 'admin'
    replicaCount: 1
    image: 'dkabh/admin:run'
    imagePullPolicy: 'IfNotPresent'
    containerPort: '9101'
  svc:
    name: 'admin-svc'
    port: '9101'
    type: 'ClusterIP'

# ----- News -----

news:
  enabled: true
  newsUrl: 'http://demoapp.abh/news'
  dep:
    name: 'news'
    labelName: 'news'
    replicaCount: 1
    image: 'dkabh/news:run'
    imagePullPolicy: 'IfNotPresent'
    containerPort: '9201'
  svc:
    name: 'news-svc'
    port: '9201'
    type: 'ClusterIP'
