# helm install elastic/logstash -f values.yaml --name=logstash
persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
logstashPipeline:
  uptime.conf: |
    #input {
        #beats {
            #port => "5044"
        #}
    #}

    #filter { }

    output {
        elasticsearch { 
            hosts => ["http://elasticsearch-master:9200"] index => "logstash" 
        }
    }
service: 
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
