{{- if .Values.biz.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.biz.dep.name }}
spec:
  replicas: {{ .Values.biz.dep.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.biz.dep.labelName }}
  template:
    metadata:
      labels:
        name: {{ .Values.biz.dep.labelName }}
    spec:
      initContainers:  # check if DB is ready, and only continue when true
      - name: check-db-ready
        image: postgres:10
        command: ['sh', '-c', 'until pg_isready -h {{ .Values.postgres.svc.name }} -p {{ .Values.postgres.svc.port }};  do echo waiting for database; sleep 2; done;']
      containers:
        - name: biz
          image: {{ .Values.biz.dep.image }}
          imagePullPolicy: {{ .Values.biz.dep.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.biz.dep.containerPort }}
          env:
            - name: BIZ_PORT
              value: {{ .Values.biz.dep.containerPort | quote }}
            - name: DB_URL
              value: {{ .Values.biz.dep.dbURL | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
{{- end }}
