{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.svc.name }}
spec:
  selector:
    name: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.svc.port }}
      targetPort: {{ .Values.postgres.svc.port }}
      name: postgres
      type: {{ .Values.postgres.svc.type }}
{{- end }}
