apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  username: {{ .Values.secrets.username | default "ZGVtbw==" | quote }}
  password: {{ .Values.secrets.password | default "ZGVtbw==" | quote }}
  db: {{ .Values.secrets.db | default "ZGVtbw==" | quote }}
